//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTEP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTEMPEntities : DbContext
    {
        public CTEMPEntities()
            : base("name=CTEMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academy> Academies { get; set; }
        public virtual DbSet<ClassName> ClassNames { get; set; }
        public virtual DbSet<Community> Communities { get; set; }
        public virtual DbSet<CourseTemp> CourseTemps { get; set; }
        public virtual DbSet<Evalution> Evalutions { get; set; }
        public virtual DbSet<EvalutionForm> EvalutionForms { get; set; }
        public virtual DbSet<EvalutionTemp> EvalutionTemps { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<University> Universities { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserBundTable> UserBundTables { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    }
}
