//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvalutionTemp
    {
        public int ID { get; set; }
        public string S_Desc { get; set; }
        public Nullable<int> I_CREATE_UID { get; set; }
        public Nullable<int> I_Type { get; set; }
        public Nullable<System.DateTime> TIME_CREATE { get; set; }
        public Nullable<double> F_Score { get; set; }
        public Nullable<int> C_STA { get; set; }
        public Nullable<double> F_TeachObj { get; set; }
        public Nullable<double> F_TeachMethod { get; set; }
        public Nullable<double> F_TeachAbility { get; set; }
        public Nullable<double> F_TeachAttitude { get; set; }
        public Nullable<double> F_StudentRelation { get; set; }
    }
}
