//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBundTable
    {
        public int ID { get; set; }
        public Nullable<int> I_UID { get; set; }
        public Nullable<int> I_Type { get; set; }
        public Nullable<int> I_BD_ID { get; set; }
    }
}
